language: node_js

branches:
  except:
    - release

node_js:
  - "node"
  - "6.10.0"

matrix:
  allow_failures:
    - node_js: nightly

addons:
  apt:
    packages:
    - build-essential


install:
  - npm install
  - if [ "$TRAVIS_NODE_VERSION" = "node" ]; then npm install --only=dev; fi;

script:
  - npm test
  - if [ "$TRAVIS_NODE_VERSION" = "node" ]; then npm run cover; fi;

after_success:
  - if [ "$TRAVIS_NODE_VERSION" = "node" ]; then cat ./coverage/lcov.info | ./node_modules/.bin/coveralls; fi
